export const impressungText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque vestibulum, sapien id semper egestas, lorem neque consectetur tortor, vel finibus ex elit eget erat. Donec eu rhoncus sapien, bibendum luctus nibh. Sed ut nisl nec odio venenatis venenatis. Sed volutpat enim sem. Morbi auctor sapien tincidunt magna semper dignissim. Morbi eget posuere tortor. Maecenas arcu urna, iaculis ut felis non, pulvinar lobortis enim. Nulla eget ultricies odio. Aenean sodales enim nec nibh consectetur lacinia. Nam 
nulla turpis, lacinia quis lacus ut, bibendum bibendum erat. In volutpat dolor nec eros faucibus gravida. Nullam non varius augue. Nullam ac mauris turpis. Duis facilisis, magna ut dapibus vehicula, orci magna luctus quam, sed imperdiet arcu eros ut mauris.

Nullam convallis a ipsum id blandit. Sed ut tortor eu tortor iaculis suscipit eget id augue. Mauris posuere, lacus et malesuada volutpat, neque mi pharetra erat, vestibulum molestie dui erat sit amet risus. Sed eget sem ut orci feugiat dictum. Sed varius mollis est in tristique. Donec pretium felis nec gravida dictum. Proin imperdiet sagittis arcu sed molestie. Praesent eu odio nunc. Vestibulum suscipit lorem tortor, sit amet faucibus turpis suscipit vel. Integer rhoncus est et arcu fringilla gravida. In hac habitasse platea dictumst.

Sed maximus ligula orci, eget pulvinar nunc suscipit vitae. Duis ipsum nunc, hendrerit quis maximus vitae, euismod sagittis erat. Ut vehicula in nibh eu ultrices. Aliquam id arcu quis lorem varius condimentum. Phasellus nec eleifend ex. Nullam at faucibus sem. Nullam ut nibh fermentum, varius libero convallis, posuere dolor. Vestibulum tincidunt eget quam et congue. Suspendisse eget ipsum vel massa laoreet vestibulum quis at metus. Sed tristique eros lacinia, facilisis velit in, malesuada elit.

Donec ut molestie eros. Morbi magna eros, pretium a metus sed, tempus tristique mi. Nullam sit amet leo sed nisi lacinia gravida. Praesent tempor tincidunt porta. Quisque elementum mauris ut aliquam porta. Ut laoreet ut velit quis laoreet. Suspendisse elementum nibh et dapibus consequat. Duis et nisl vel mi volutpat dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Aliquam enim leo, pharetra vel ligula a, blandit venenatis augue.

Curabitur id dui ut turpis sagittis dapibus et a sem. Integer dapibus consequat tortor sit amet aliquam. Proin efficitur, mauris non sodales condimentum, purus eros tempor urna, sed ullamcorper risus justo sed libero. Etiam lobortis hendrerit aliquam. Donec ac mi eu ipsum auctor tempus. Praesent a imperdiet nunc. Nulla risus purus, accumsan eu ex sed, semper tristique lectus.

`;
